tests:
  summary: Run the test suite
  command: go test -v {{.files}}

install-deps:
  summary: Install all of package dependencies
  command: go get -t {{.files}}

variables:
  files: '$(go list -v ./... | grep -Ev "github.com/alecaivazis/survey/(tests|examples)")'
